<?php $this->headTitle($this->translate('Participating Institutions')); ?>
<h1>
<?=$this->
	transEsc('Participating Institutions') ?> 
</h1>
<p>
	This is a list of all the institutions providing content via the "Catholic Portal". 
</p>
<a name="bar"></a> 
	<h2>Barry University</h2>
<p>
	<strong>Monsignor William Barry Memorial Library</strong>
</p>
<p>
	11300 NE 2nd Avenue<br />
	Miami Shores, FL 33161<br />
	Reference: (305) 899-3772; Public Services: (305) 899-3760; Toll-free: 1 (800) 756-6000, ext. 3760<br />
	<a href="mailto:library@mail.barry.edu">library@mail.barry.edu</a><br />
	<a href="http://www.barry.edu/library-services/" target="_blank">http://www.barry.edu/library-services/</a> 
</p>
<a name="bcu"></a> 
<h2>
	Boston College
</h2>
<p>
	<strong>John J. Burns Library</strong>
</p>
<p>
	140 Commonwealth Avenue<br />
	Chestnut Hill, MA 02467<br />
	(617) 552-4861<br />
	<a href="mailto:burnsref@bc.edu">burnsref@bc.edu</a><br />
	<a href="http://libguides.bc.edu/burns" target="_blank">http://libguides.bc.edu/burns</a> 
</p>
<a name="ben"></a> 
<h2>
	Benedictine University
</h2>
<p>
	<strong>Benedictine University Library</strong>
</p>
<a name="bvm"></a> 
<h2>
	Sisters of Charity
</h2>
<p>
	<strong>BVM Congregation Archives</strong>
</p>
<p>
	1100 Carmel Drive<br />
	Dubuque, Iowa 52003-7991<br />
	(563) 588-2351<br />
	<a href="mailto:jhead@bvmcong.org">jhead@bvmcong.org</a><br />
	<a href="http://www.bvmcong.org" target="_blank">http://www.bvmcong.org</a> 
</p>
<a name="ctu"></a> 
<h2>
	Catholic Theological Union
</h2>
<p>
	<strong>Paul Bechtold Library</strong>
</p>
<p>
	5401 S. Cornell<br />
	Chicago IL 60615<br />
	(773) 371-5460<br />
	<a href="mailto:mmcmahon@ctu.edu">mmcmahon@ctu.edu</a><br />
	<a href="http://www.ctu.edu/library" target="_blank">http://www.ctu.edu/library</a> 
</p>
<a name="cua"></a> 
<h2>
	The Catholic University of America
</h2>
<p>
	<strong>University Libraries</strong>
</p>
<p>
	The Catholic University of America<br />
	Washington, D.C. 20064<br />
	(202) 319-5070<br />
	<a href="http://libraries.cua.edu" target="_blank">http://libraries.cua.edu</a> 
</p>
<a name="doc"></a> 
<h2>
	Daughters of Charity
</h2>
<p>
	<strong>Daughters of Charity Provincial Archives</strong>
</p>
<p>
	341 South Seton Avenue<br />
	Emmitsburg, MD 21727<br />
	(301) 447-6041<br />
	<a href="mailto:archives@doc.org">archives@doc.org</a><br />
	<a href="http://daughtersofcharity.org/our-legacy/" target="_blank">http://daughtersofcharity.org/our-legacy/</a> 
</p>
<a name="dep"></a> 
<h2>
	DePaul University
</h2>
<p>
	<strong>John T. Richardson Library</strong>
</p>
<p>
	25 E Jackson Blvd.<br />
	Chicago, IL 60604<br />
	(773) 325-7863<br />
	<a href="http://library.depaul.edu/" target="_blank">http://library.depaul.edu/</a> 
</p>

<a name="dom"></a> 
<h2>
	Dominican University
</h2>
<p>
	<strong>Rebecca Crown Library</strong>
</p>
<p>
	7900 W. Division<br />
	River Forest, IL 60305<br />
	(708) 524-6875<br />
	<a href="mailto:reference@dom.edu">reference@dom.edu</a><br />
	<a href="http://www.dom.edu/library" target="_blank">http://www.dom.edu/library</a> 
</p>

<a name="day"></a> 
<a name="dua"></a> 
<a name="dus"></a> 
<h2>
	University of Dayton
</h2>
<p>
	<strong>The Marian Library</strong>
</p>
<p>
	300 College Park<br />
	Dayton, OH 45469-1390<br />
	(937) 229-4214<br />
	<a href="http://campus.udayton.edu/mary/" target="_blank">http://campus.udayton.edu/mary/</a>
</p>

<p>
	<strong>University Archives</strong>
</p>
<p>
	300 College Park<br />
	Dayton, OH 45469-1360<br />
	(937) 229-4256<br />
	<a href="mailto:archives@udayton.edu">archives@udayton.edu</a><br />
	<a href="http://www.udayton.edu/libraries/archives_and_collections/index.php#1" target="_blank">http://www.udayton.edu/libraries/archives_and_collections/index.php#1</a> 
</p>

<p>
	<strong>US Catholic Collection</strong>
</p>
<p>
	300 College Park<br />
	Dayton, OH 45469-1360<br />
	(937) 229-4262<br />
	<a href="mailto:nhary1@udayton.edu">nhary1@udayton.edu</a><br />
	<a href="http://www.udayton.edu/libraries/archives_and_collections/index.php#3" target="_blank">http://www.udayton.edu/libraries/archives_and_collections/index.php#3</a> 
</p>
<a name="edc"></a> 
<h2>
	Edgewood College
</h2>
<p>
	<strong>Oscar Rennebohm Library</strong>
</p>
<p>
	959 Edgewood College Drive<br />
	Madison, WI 53711<br />
	(608) 663-3300<br />
	<a href="mailto:LibAnswers@edgewood.edu">LibAnswers@edgewood.edu</a><br />
	<a href="https://library.edgewood.edu/home" target="_blank">https://library.edgewood.edu/home</a> 
</p>
<a name="fbu"></a> 
<h2>
	Fontbonne University
</h2>
<p>
	<strong>Jack C. Taylor Library</strong>
</p>
<p>
	6800 Wydown Blvd.<br />
	St. Louis, MO 63105<br />
	(314)719-8046<br />
	archives@fontbonne.edu<br />
	<a href="https://library.fontbonne.edu" target="_blank"">https://library.fontbonne.edu</a> 
</p>
<a name="gtu"></a> 
<h2>
	Georgetown University
</h2>
<p>
	<strong>Lauinger Library, Special Collections Research Center</strong>
</p>
<p>
	37th and O Streets, NW<br />
	Washington, DC 20057<br />
	(202) 687-7444<br />
	<a href="mailto:speccoll@georgetown.edu">speccoll@georgetown.edu</a><br />
	<a href="http://www.library.georgetown.edu/special-collections" target="_blank">http://www.library.georgetown.edu/special-collections</a> 
</p>
<a name="hly"></a> 
<h2>
	College of the Holy Cross
</h2>
<p>
	<strong>Library Services</strong>
</p>
<p>
	One College Street<br />
	Worcester, Mass. 01610<br />
	(508) 793-2520<br />
	<a href="mailto:kreilly@holycross.edu">kreilly@holycross.edu</a><br />
	<a href="http://www.holycross.edu/support-and-resources/holy-cross-libraries" target="_blank">http://www.holycross.edu/support-and-resources/holy-cross-libraries</a> 
</p>
<a name="jmc"></a> 
<h2>
	Jacques Maritain Center
</h2>
<p>
	430 Geddes Hall<br />
	Notre Dame, IN 46556 
</p>
<a name="lmu"></a> 
<h2>
	Loyola Marymount University
</h2>
<p>
	<strong>William H. Hannon Library</strong>
</p>
<p>
	1 LMU Drive<br />
	Los Angeles, CA 90045<br />
	(310) 338-2788<br />
	<a href="mailto:library@lmu.edu">library@lmu.edu</a><br />
	<a href="http://library.lmu.edu/" target="_blank">http://library.lmu.edu/</a> 
</p>
<a name="lul"></a> <a name="luw"></a> <a name="luc"></a> 
<h2>
	Loyola University Chicago
</h2>
<p>
	<strong>Women and Leadership Archives, Piper Hall</strong>
</p>
<p>
	1032 W. Sheridan Road<br />
	Chicago, IL 60660<br />
	(773) 508-8837<br />
	<a href="mailto:wlarchives@luc.edu">wlarchives@luc.edu</a><br />
	<a href="http://www.luc.edu/wla" target="_blank">http://www.luc.edu/wla</a> 
</p>
<a name="mar"></a> 
<h2>
	Marquette University
</h2>
<p>
	<strong>Raynor Memorial Libraries, Special Collections and University Archives</strong>
</p>
<p>
	1355 W. Wisconsin Avenue<br />
	P.O. Box 3141<br />
	Milwaukee, WI 53201-3141<br />
	(414) 288-7256<br />
	<a href="mailto:william.fliss@marquette.edu">william.fliss@marquette.edu</a><br />
	<a href="http://www.marquette.edu/library/archives/" target="_blank">http://www.marquette.edu/library/archives/</a> 
</p>
<a name="msm"></a> 
<h2>
	Mount Saint Mary's University
</h2>
<p>
	<strong>Phillips Library</strong>
</p>
<p>
	Emmitsburg, MD 21727<br />
	(301) 447-5242<br />
	<a href="mailto:yelovich@msmary.edu">yelovich@msmary.edu</a><br />
	<a href="http://www.msmary.edu/academics/library/" target="_blank">http://www.msmary.edu/academics/library/</a> 
</p>
<a name="olv"></a> 
<h2>
	Our Lady of Victory Missionary Sisters
</h2>
<p>
	1900 W Park Drive<br />
	Huntington, IN 46750<br />
	<a href="mailto:jhoffman@olvm.org">jhoffman@olvm.org</a><br />
	<a href="http://www.olvm.org" target="_blank">http://www.olvm.org</a> 
</p>
<a name="pah"></a> 
<h2>
	Philadelphia Archdiocesan Historical Research Center
</h2>
<p>
	100 E. Wynnewood Rd.<br />
	Wynnewood, PA 19096<br />
	(610) 667-2125<br />
	<a href="mailto:pahrc89@gmail.com">pahrc89@gmail.com</a><br />
	<a href="http://www.pahrc.net" target="_blank">http://www.pahrc.net</a> 
</p>
<a name="reg"></a> 
<h2>
	Regis University
</h2>
<p>
	<strong>Dayton Memorial Library</strong>
</p>
<p>
	3333 Regis Blvd., D-20<br />
	Denver, CO 80221<br />
	(303) 964-4031<br />
	<a href="mailto:library@regis.edu">library@regis.edu</a><br />
	<a href="http://www.regis.edu/library/" target="_blank">http://www.regis.edu/library/</a> 
</p>
<a name="sed"></a> 
<h2>
	Saint Edward's University
</h2>
<p>
	<strong>Library</strong>
</p>
<p>
	3001 South Congress Av.<br />
	Austin, TX 78704-6489<br />
	(512) 428-1047<br />
	<a href="mailto:aprils@stedwards.edu">aprils@stedwards.edu</a><br />
	<a href="http://library.stedwards.edu/" target="_blank">http://library.stedwards.edu/</a> 
</p>
<a name="shu"></a> 
<h2>
	Seton Hall University
</h2>
<p>
	<strong>Walsh Library</strong>
</p>
<p>
	400 South Orange Avenue<br />
	South Orange, NJ 07079 
</p>
<a name="sjc"></a> 
<h2>
	St. Joseph's College
</h2>
<p>
	<strong>McEntegart Hall Library</strong>
</p>
<p>
	222 Clinton Avenue<br />
	Brooklyn, New York 11205 <br />
	Reference questions: (718) 940-5880; Circulation inqueries: (718) 940-5878<br />
	<a href="mailto:bklibrary@sjcny.edu">bklibrary@sjcny.edu</a><br />
	<a href="http://mcentegart.sjcny.edu/MainPage/Home-Page/1167/" target="_blank">http://mcentegart.sjcny.edu/MainPage/Home-Page/1167/</a> 
</p>
<a name="sjn"></a> <a name="sju"></a> 
<h2>
	Saint Joseph's University
</h2>
<p>
	<strong>Post Learning Commons and Drexel Library</strong>
</p>
<p>
	Archives and Special Collections<br />
	5600 City Ave.<br />
	Philadelphia, PA. 19131<br />
	<a href="mailto:archive@sju.edu">archive@sju.edu</a><br />
	<a href="http://www.sju.edu/int/resources/libraries/drexel/archives/" target="_blank">http://www.sju.edu/int/resources/libraries/drexel/archives/</a> 
</p>
<a name="slu"></a> <a name="snc"></a> 
<h2>
	St. Norbert College
</h2>
<p>
	<strong>Mulva Library</strong>
</p>
<p>
	100 Grant Street<br />
	De Pere, WI 54115<br />
	(920) 403-3270<br />
	<a href="mailto:rochelle.vanerem@snc.edu">rochelle.vanerem@snc.edu</a><br />
	<a href="http://www.snc.edu/library/" target="_blank">http://www.snc.edu/library/</a> 
</p>
<a name="stc"></a> 
<h2>
	St. Catherine University
</h2>
<p>
	<strong>St. Catherine University Libraries</strong>
</p>
<p>
	2004 Randolph Avenue<br />
	St. Paul, MN 55105<br />
	(651) 690-6553<br />
	<a href="mailto:archives@stkate.edu">archives@stkate.edu</a><br />
	<a href="http://library.stkate.edu/spcoll/main.html" target="_blank">http://library.stkate.edu/spcoll/main.html</a> 
</p>
<a name="stm"></a> 
<h2>
	University of St. Thomas
</h2>
<p>
	<strong>University of St. Thomas Library</strong>
</p>
<p>
	Department of Special Collections<br />
	2115 Summit Avenue<br />
	Saint Paul, MN 55105-1096<br />
	(651) 962-5467<br />
	<a href="mailto:uarchives@stthomas.edu">uarchives@stthomas.edu</a><br />
	<a href="http://www.stthomas.edu/libraries/special/" target="_blank">http://www.stthomas.edu/libraries/special/</a> 
</p>
<a name="tor"></a> 
<h2>
	The University of St. Michael's College
</h2>
<p>
	<strong>The John M. Kelly Library</strong>
</p>
<p>
	113 St. Joseph Street<br />
	Toronto, Ontario M5S 1J4, Canada<br />
	(416) 926-7114<br />
	<a href="http://stmikes.utoronto.ca/kelly/contact/" target="_blank">http://stmikes.utoronto.ca/kelly/contact/</a> 
</p>
<a name="una"></a> 
<a name="und"></a> 
<h2>
	University of Notre Dame
</h2>
<p>
	<strong>University of Notre Dame Archives</strong>
</p>
<p>
	607 Hesburgh Library<br />
	Notre Dame, IN 46556<br />
	(574) 631-6448<br />
	<a href="mailto:archives@nd.edu">archives@nd.edu</a><br />
	<a href="http://archives.nd.edu/" target="_blank">http://archives.nd.edu/</a> 
</p>

<p>
	<strong>Rare Books &amp; Special Collections</strong>
</p>
<p>
	102 Hesburgh Library<br />
	Notre Dame, IN 46556<br />
	(574) 631-0290<br />
	<a href="mailto:rarebook@nd.edu">rarebook@nd.edu</a><br />
	<a href="http://www.library.nd.edu/rarebooks/" target="_blank">http://www.library.nd.edu/rarebooks/</a> 
</p>
<a name="usd"></a> 
<h2>
	University of San Diego
</h2>
<p>
	<strong>Copley Library</strong>
</p>
<p>
	5998 Alcala Park<br />
	San Diego, CA 92110-2492<br />
	(619) 260-4721<br />
	<a href="mailto:diane@sandiego.edu">diane@sandiego.edu</a><br />
	<a href="http://www.sandiego.edu/library/about/collections.php" target="_blank">http://www.sandiego.edu/library/about/collections.php</a> 
</p>
<a name="usf"></a> 
<h2>
	University of San Francisco
</h2>
<p>
	<strong>Gleeson Library</strong>
</p>
<p>
	2130 Fulton Street<br />
	San Francisco, CA 94117-1049<br />
	(415) 422-2660<br />
	<a href="mailto:reference@usfca.edu">reference@usfca.edu</a><br />
	<a href="https://www.usfca.edu/library" target="_blank">https://www.usfca.edu/library</a> 
</p>
<a name="vil"></a> 
<h2>
	Villanova University
</h2>
<p>
	<strong>Falvey Memorial Library</strong>
</p>
<p>
	800 Lancaster Avenue<br />
	Villanova, PA 19085<br />
	(610) 519-4270<br />
	<a href="mailto:ref@villanova.edu">ref@villanova.edu</a><br />
	<a href="https://library.villanova.edu" target="_blank">https://library.villanova.edu</a> 
</p>
