<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
        <p><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></p>
        <p><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></p>
        <p><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></p>
        <p><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></p>
        <p><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></p>
        <p><a href="https://catholicresearch.org/">Return to main CRRA website</a></p>
    </div>
    <div class="footer-column">
        <p>&copy; 2023 Copyright Atla.</p>
        <p>
		<a href="https://www.catholicresearch.org/ask-us">
			<img src="<?=$this->imageLink('Ask-Us-Icon.png')?>" alt="Ask Us"/>
		</a>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>
</footer>


