<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>

<div class="row">
    <div class="col-xs-12 col-sm-9">
        <h1>Welcome to the Catholic Portal</h1>
        <p>The Catholic Research Resources Portal, or "Catholic Portal," provides access to rare, unique and/or uncommon materials in libraries, seminaries, special collections and archives. By electronically bringing together resources in many formats from many collections, the Portal enables easy, effective and global discovery of Catholic research resources.</p>
    </div>
</div>
<div class="searchHomeContent">
  <?php $this->slot('search-home-hero')->start() ?>
    <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
  <?=$this->slot('search-home-hero')->end() ?>
</div>

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>

<div class="row">
    <div class="col-xs-12 col-sm-9">
        <h2>About the Catholic Research Resources Alliance (CRRA)</h2>
		<p>The Catholic Research Resources Alliance (CRRA) was founded in 2008 as a membership alliance of institutions committed to delivering projects and services in support of its mission to create enduring permanent global access to Catholic resources in the Americas. <a href="https://www.atla.com/blog/faq-regarding-atla-crra-exploring-a-new-path-forward-together/">In 2023, CRRA members voted to dissolve and CRRA formally became a program of Atla</a>.</p>
		<p><a href="https://www.atla.com/about/">Established in 1946 as the American Theological Library Association</a>, Atla is a membership association of librarians and information professionals, and a producer of research tools, committed to advancing the study of religion and theology. Atla’s membership includes more than 800 individuals and libraries at academic institutions from diverse religious traditions and backgrounds. As a community of collectors and connectors, Atla works to promote worldwide scholarly communication in religion and theology by advancing the work of libraries and related information providers.</p>
        <p>Through the <a href="https://www.atla.com/learning-engagement/crra/" target="_blank">CRRA program</a>, Atla will continue to offer Catholic-focused programming and networking for libraries, archives and other institutions through continued support and growth of the resources founded by CRRA and development of new initiatives with the input and guidance of its members and participants in the CRRA program.</p>
		<p><i>The original content of this webpage is below.</i></p>
        <p>The CRRA is a collaborative effort initiated by eight Catholic colleges and universities to share their resources electronically with librarians, archivists, researchers, scholars, and the general public, all who are interested in the Catholic experience. The mission of the CRRA is to provide enduring global access to Catholic research resources. Our immediate focus is creating access to those rare, unique and uncommon research materials relating to every aspect of the Catholic experience, which are held by college, university, and seminary libraries and archives in North America.</p>
        <p><a href="<?=$this->url('content-page', ['page' => 'institutions']) ?>"><?=$this->transEsc('View Participating Institutions')?></a></p>
        <p><a href="https://atla.libguides.com/catholic-portal-contribute">Contribute to the Catholic Portal.</a>
    </div>
</div>

